[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "https://goobismoobis.com/assets/goobismoobis2logo.png"

[footer]
style = "dark"
copyright = "Copyright © 2026 GoobisMoobis. Built with Moonwave and Docusaurus"

[[footer.links]]
title = "Links"

[[footer.links.items]]
label = "My Website"
href = "https://goobismoobis.com/"

[[footer.links.items]]
label = "GitHub"
href = "https://github.com/GoobisMoobis"
